name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-mingw:
    name: Build (MinGW-w64)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2 (MinGW-w64)
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Build with MinGW-w64
      shell: msys2 {0}
      run: |
        cd build
        make clean
        make
        ls -lh ../bin/mousejiggler.exe

    - name: Validate executable
      shell: msys2 {0}
      run: |
        echo "Testing --version flag..."
        ../bin/mousejiggler.exe --version
        echo "Testing --help flag..."
        ../bin/mousejiggler.exe --help

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mousejiggler-mingw64-${{ github.sha }}
        path: bin/mousejiggler.exe
        retention-days: 90

  build-msvc:
    name: Build (MSVC)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with MSVC
      shell: cmd
      run: |
        cd build
        call build.bat
        dir ..\bin\mousejiggler.exe

    - name: Validate executable
      shell: cmd
      run: |
        echo Testing --version flag...
        bin\mousejiggler.exe --version
        echo Testing --help flag...
        bin\mousejiggler.exe --help

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mousejiggler-msvc-${{ github.sha }}
        path: bin/mousejiggler.exe
        retention-days: 90

  release:
    needs: [build-mingw, build-msvc]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/mousejiggler.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
